# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "7a67c1fa7066b89ae86509c91d8f5b6f"
name = "LLM Text Generator"
handle = "llm-txt-mc"
application_url = "https://apply-suspended-billion-leaf.trycloudflare.com/"
embedded = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  uri = "/webhook/customers-data-request"
  compliance_topics = [ "customers/data_request" ]

  [[webhooks.subscriptions]]
  uri = "/webhook/customers-redact"
  compliance_topics = [ "customers/redact" ]

  [[webhooks.subscriptions]]
  uri = "/webhook/shop-redact"
  compliance_topics = [ "shop/redact" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products,read_online_store_pages,read_content"

[auth]
redirect_urls = [ "https://apply-suspended-billion-leaf.trycloudflare.com/authenticate" ]

[app_proxy]
url = "https://apply-suspended-billion-leaf.trycloudflare.com/check-limit-proxy"
subpath = "llms"
prefix = "a"

[pos]
embedded = false

[build]
include_config_on_deploy = true
